### ISSUE TITLE
Post: Noch 30 Tage

### ISSUE THREAD

**Issue by TheyKnowWhatIsWhat** [TheyKnowWhatIsWhat/BurningBeachSocial#1]
Text
Der Countdown läuft🌴
Nur noch 30 Tage bis zum Burning Beach Festival am Brombachsee!

Mit welchem deiner Rave-Buddies möchtest du in einem Monat barfuß am Strand tanzen?
Sichere dir JETZT dein Ticket für 3-Tage Festivalurlaub!

**Comment by Milanmilano1** [comment]
Top sollte klappen

**Comment by TheyKnowWhatIsWhat** [comment]
![Image](https://github.com/TheyKnowWhatIsWhat/BurningBeachSocial/assets/166693939/a081268c-b4c6-4e90-a50a-6dff6f114c21)
