### ISSUE TITLE
Noch 20 Tage

### ISSUE THREAD

**Issue by TheyKnowWhatIsWhat** [TheyKnowWhatIsWhat/BurningBeachSocial#17]
Nur noch 20 Tage! Die Vorbereitungen gehen in die heiße Phase und wer gut hinhört, kann die Bässe schon wummern hören!

Nicht mehr lang bis wir uns alle am Brombachsee endlich (wieder) sehen 🤗
Wie oft warst du schon beim Burning Beach dabei oder ist es dein erstes Mal?

Hol dir jetzt dein Ticket für 3 Tage Festival-Sommer am Brombachsee.

**Comment by TheyKnowWhatIsWhat** [comment]
Text noch nicht final, war recht high

**Comment by Milanmilano1** [comment]
Wann sind die 20 Tage ?

**Comment by TheyKnowWhatIsWhat** [comment]
Habe ich bei Start Date hinterlegt

25.5

**Comment by TheyKnowWhatIsWhat** [comment]
![Image](https://github.com/TheyKnowWhatIsWhat/BurningBeachSocial/assets/166693939/44993664-6aef-4fa3-9187-25c898335e50)

**Comment by TheyKnowWhatIsWhat** [comment]
@Milanmilano1 bernhard meinte er hätte gerne, dass das 20 tag im profil zu lesen ist.

**Comment by Milanmilano1** [comment]
Ok 

Haben wie vorher nochmal ein Foto ?

**Comment by Milanmilano1** [comment]
Ansonsten würd ich gern ein kleines Label Feature morgen zwischen schieben mit passendem Bild

**Comment by TheyKnowWhatIsWhat** [comment]
Lass n video posten ich schau mal eben
