### ISSUE TITLE
Post: Timetable

### ISSUE THREAD

**Issue by TheyKnowWhatIsWhat** [TheyKnowWhatIsWhat/BurningBeachSocial#3]
Text:

Stifte gezückt✏️ 
Hier kommt der Timetable für den Burning Beach 2024 🥵

Zum Timetable Release verschenken wir 2x2 Tagestickets für einen Tag deiner Wahl.
1) ❤️ den Beitrag
2) Schreibe in den Kommentaren mit wem du an welchem Tag am Beach tanzen möchtest!

Ab 18 Jahren. Einsendeschluss ist der xxxxxxx!

**Comment by Milanmilano1** [comment]
Wann posten wir den timetable ?

**Comment by TheyKnowWhatIsWhat** [comment]
https://github.com/TheyKnowWhatIsWhat/BurningBeachSocial/assets/166693939/e8b1a66a-d3d2-453b-842b-570aa624fecf
